-- MySQL Script generated by MySQL Workbench
-- 07/10/15 15:29:44
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`portfolio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`portfolio` ;

CREATE TABLE IF NOT EXISTS `mydb`.`portfolio` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(100) NULL COMMENT '',
  `description` TEXT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`portfolio_image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`portfolio_image` ;

CREATE TABLE IF NOT EXISTS `mydb`.`portfolio_image` (
  `image_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `title` VARCHAR(200) NULL COMMENT '',
  `description` TEXT NULL COMMENT '',
  `portofolio_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`image_id`, `portofolio_id`)  COMMENT '',
  INDEX `fk_portofolio_image_portofolio_idx` (`portofolio_id` ASC)  COMMENT '',
  CONSTRAINT `fk_portofolio_image_portofolio`
    FOREIGN KEY (`portofolio_id`)
    REFERENCES `mydb`.`portfolio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`projectType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`projectType` ;

CREATE TABLE IF NOT EXISTS `mydb`.`projectType` (
  `id` TINYINT NOT NULL COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`customerMessage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`customerMessage` ;

CREATE TABLE IF NOT EXISTS `mydb`.`customerMessage` (
  `customerMessage_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(100) NULL COMMENT '',
  `address` TEXT NULL COMMENT '',
  `email` VARCHAR(100) NULL COMMENT '',
  `projectType_id` TINYINT NOT NULL COMMENT '',
  `description` TEXT NULL COMMENT '',
  `start_date` DATETIME NULL COMMENT '',
  `end_date` DATETIME NULL COMMENT '',
  `budget` TEXT NULL COMMENT '',
  `message_type` SMALLINT NULL COMMENT '',
  PRIMARY KEY (`customerMessage_id`, `projectType_id`)  COMMENT '',
  INDEX `fk_customerMessage_projectType1_idx` (`projectType_id` ASC)  COMMENT '',
  CONSTRAINT `fk_customerMessage_projectType1`
    FOREIGN KEY (`projectType_id`)
    REFERENCES `mydb`.`projectType` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
